### ISSUE TITLE
_plot_raxis must be updated

### ISSUE THREAD

**Issue by ijunier** [TrEE-TIMC/circhic#40]
- it currently displays only 60 kb and 120 kb
- the code is wrong for the distant mode (see attached example for disattn from 0 to 2000 kb in principle)
- I would not use a bold fontweigh for the label (the same for the cbar)

[ccrescentus_circhic_#2B.pdf](https://github.com/TrEE-TIMC/circhic/files/4777387/ccrescentus_circhic_.2B.pdf)

**Comment by ijunier** [comment]
Still bugging (cf figure)

[ccrescentus_circhic_#2.pdf](https://github.com/TrEE-TIMC/circhic/files/4792155/ccrescentus_circhic_.2.pdf)

**Comment by ijunier** [comment]
Ticks work on 'distant' mode. But pb with tick labels as in 'reflect' mode

[ccrescentus_circhic_#3.pdf](https://github.com/TrEE-TIMC/circhic/files/4792165/ccrescentus_circhic_.3.pdf)

**Comment by NelleV** [comment]
I think this is due to the resolution : if you provide inner_gdis and
outer_gdis at the bin level, the code converts those in kb, which makes
them below 0.
Let's leave this open for now: we need a smarter conversion from unit to
axis or just remove any conversion and let the user deal with it (as in
"normal" matplotlib)

**Comment by NelleV** [comment]
This is fixed: it doesn't do anything smart by default and assumes the user is going to specify ticklabels if it is not in the coordinate format.
cf #52
